const fs = require('fs');
const { JSDOM } = require('jsdom');
const htmlSrc = fs.readFileSync('index.html','utf8');
const configSrc = fs.readFileSync('js/supabase-config.js','utf8');
const cloudSrc = fs.readFileSync('js/cloud.js','utf8');
const appSrc = fs.readFileSync('js/app.js','utf8');
const serverRows = []; let listeners = [];
function makeServerClient(){ return { from(t){ return { select(){return Promise.resolve({data:JSON.parse(JSON.stringify(serverRows)),error:null});}, upsert(row){ const i=serverRows.findIndex(r=>r.k===row.k); if(i>=0)Object.assign(serverRows[i],row); else serverRows.push({...row}); listeners.forEach(f=>{try{f();}catch{}}); return Promise.resolve({error:null}); } }; }, channel(){return{on(){return this;},subscribe(){return this;}};} }; }
const dom = new JSDOM(htmlSrc,{runScripts:'outside-only',pretendToBeVisual:true});
const w=dom.window; w.confirm=()=>true; w.alert=()=>{}; w.matchMedia=w.matchMedia||(()=>({matches:false,addListener(){},removeListener(){}}));
w.supabase={createClient:()=>makeServerClient()};
w.eval(configSrc); w.eval(cloudSrc); w.eval(appSrc);
const wait=ms=>new Promise(r=>setTimeout(r,ms));
(async()=>{
  await w.CloudStore.ready;
  w.document.querySelector('#password-input').value='Deepnectar@1612@';
  w.document.querySelector('#login-btn').click();
  await wait(400);
  console.log('pages after login:', [...w.document.querySelectorAll('.page')].map(p=>p.id).join(','));
  const host=w.document.createElement('div');
  host.innerHTML='<button id="empty-blank-btn" type="button">➕ Add blank day</button>';
  w.document.body.appendChild(host);
  w.document.getElementById('empty-blank-btn').click();
  await wait(300);
  console.log('pages after add:', [...w.document.querySelectorAll('.page')].map(p=>p.id).join(','));
  const dayNewA=w.document.getElementById('day2')||w.document.getElementById('day1');
  console.log('using day id:', dayNewA && dayNewA.id);
  const textInputs=[...dayNewA.querySelectorAll('input[type="text"], textarea')];
  console.log('text inputs count:', textInputs.length, 'first has dhk:', textInputs[0] && textInputs[0].getAttribute('data-dhk'));
  const ta=dayNewA.querySelector('textarea')||textInputs[textInputs.length-1];
  const inp=textInputs[0];
  inp.value='Rope bonding, blindfold, slow Sunday';
  inp.dispatchEvent(new w.Event('input',{bubbles:true}));
  ta.value='Aftercare: warm cocoa, cuddles, hair brushing';
  ta.dispatchEvent(new w.Event('input',{bubbles:true}));
  const saveBtnA=w.document.querySelector('#save-contract');
  saveBtnA.click();
  await wait(3000);
  console.log('toast:', w.document.querySelector('#toast').textContent);
  const fieldsRow=serverRows.find(r=>r.k==='fields');
  console.log('fields row present:', !!fieldsRow, 'type:', fieldsRow && typeof fieldsRow.v);
  const fkeys=fieldsRow?Object.keys(fieldsRow.v):[];
  console.log('total field keys:', fkeys.length, 'day-prefixed:', fkeys.filter(k=>/^day\d+~/.test(k)).slice(0,5));
  console.log('has typed value anywhere:', fkeys.some(k=>fieldsRow.v[k]==='Rope bonding, blindfold, slow Sunday'));
  console.log('inp dhk now:', inp.getAttribute('data-dhk'), 'key would be:', dayNewA.id+'~'+inp.getAttribute('data-dhk'));
  const daysRow=serverRows.find(r=>r.k==='days');
  console.log('days row:', daysRow && daysRow.v.map(d=>d.id).join(','));
  process.exit(0);
})().catch(e=>{console.log('FATAL',e.stack);process.exit(1)});
